codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches:
          - "master"
          - "1.x"
          - "2.x"
          - "release-*"
